# Generated by Django 5.1.6 on 2025-02-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('description', models.CharField(max_length=50)),
                ('imageUrl', models.CharField(max_length=60)),
                ('isActive', models.BooleanField(default=True)),
                ('slug', models.SlugField(blank=True, default='', unique=True)),
            ],
        ),
    ]
