# Generated by Django 5.1.6 on 2025-02-22 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_adress_category_product_categories_supplier_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supplier',
            old_name='adress',
            new_name='address',
        ),
    ]
